export const class3Students = [
  {roll: 1, studentName: 'ସୁମନ ବେହେରା', class: 3},
  {roll: 2, studentName: 'ରାଜେଶ ନାୟକ', class: 3},
  {roll: 3, studentName: 'ଲିପିକା ମୁର୍ମୁ', class: 3},
  {roll: 4, studentName: 'ବିଶ୍ୱଜିତ ଦାସ', class: 3},
  {roll: 5, studentName: 'ଅଶୋକ ସୋରେନ', class: 3},
  {roll: 6, studentName: 'ପ୍ରିୟଙ୍କା ସାହୁ', class: 3},
  {roll: 7, studentName: 'ମନୋଜ ମୁଣ୍ଡା', class: 3},
  {roll: 8, studentName: 'ସବିତା ପଣିଗାହୀ', class: 3},
  {roll: 9, studentName: 'ଚିତ୍ରାଙ୍ଗଦା ମଜି', class: 3},
  {roll: 10, studentName: 'ବିକାଶ ସାହୁ', class: 3},
  {roll: 11, studentName: 'ଗୁରୁପ୍ରସାଦ ବାରିକ', class: 3},
  {roll: 12, studentName: 'ଲତା ପଟ୍ଟନାୟକ', class: 3},
  {roll: 13, studentName: 'ସୁଶାନ୍ତ ତିର୍କି', class: 3},
  {roll: 14, studentName: 'କବିତା ମିଶ୍ର', class: 3},
  {roll: 15, studentName: 'ପ୍ରଦୀପ ହେମ୍ବ୍ରମ', class: 3},
  {roll: 16, studentName: 'ଅନିତା ସାହୁ', class: 3},
  {roll: 17, studentName: 'ଜଗନ୍ନାଥ ବେଶ୍ରା', class: 3},
  {roll: 18, studentName: 'ସ୍ମିତା ପଣ୍ଡା', class: 3},
  {roll: 19, studentName: 'ମହେଶ ସୋରେନ', class: 3},
  {roll: 20, studentName: 'ଦୀପାଳି ପଟ୍ଟନାୟକ', class: 3},
  {roll: 21, studentName: 'ରାଜନୀକାନ୍ତ ମୁର୍ମୁ', class: 3},
  {roll: 22, studentName: 'ସଞ୍ଜୟ ସାହୁ', class: 3},
  {roll: 23, studentName: 'ତାରାପ୍ରସାଦ ବେହେରା', class: 3},
  {roll: 24, studentName: 'ପୂର୍ଣ୍ଣିମା ମିଶ୍ର', class: 3},
  {roll: 25, studentName: 'ଗୋବିନ୍ଦ ମୁଣ୍ଡା', class: 3},
  {roll: 26, studentName: 'ଶିବାନୀ ପଣ୍ଡା', class: 3},
  {roll: 27, studentName: 'ମିଥୁନ ହେମ୍ବ୍ରମ', class: 3},
  {roll: 28, studentName: 'ସୁଜାତା ସାହୁ', class: 3},
  {roll: 29, studentName: 'ଚନ୍ଦ୍ରମଣି ତିର୍କି', class: 3},
  {roll: 30, studentName: 'ରେଖା ପଟ୍ଟନାୟକ', class: 3},
];

export const class5Students = [
  {roll: 1, studentName: 'ସୁମିତା ପଟ୍ଟନାୟକ', class: 5},
  {roll: 2, studentName: 'ଲକ୍ଷ୍ମୀକାନ୍ତ ମୁର୍ମୁ', class: 5},
  {roll: 3, studentName: 'ବିଶାଳ ସାହୁ', class: 5},
  {roll: 4, studentName: 'ମନୋଜ ସୋରେନ', class: 5},
  {roll: 5, studentName: 'କମଳେଶ ମିଶ୍ର', class: 5},
  {roll: 6, studentName: 'ପୁଷ୍ପା ତିର୍କି', class: 5},
  {roll: 7, studentName: 'ଲତା ମହାନ୍ତି', class: 5},
  {roll: 8, studentName: 'ବିବେକାନନ୍ଦ ହେମ୍ବ୍ରମ', class: 5},
  {roll: 9, studentName: 'ଜ୍ୟୋତିର୍ମୟ ବେହେରା', class: 5},
  {roll: 10, studentName: 'ସ୍ନିଗ୍ଧା ପଣ୍ଡା', class: 5},
  {roll: 11, studentName: 'ଚିନ୍ମୟୀ ରାଉତ', class: 5},
  {roll: 12, studentName: 'ଚନ୍ଦ୍ରା ସୋରେନ', class: 5},
  {roll: 13, studentName: 'ରୋହିତ ପାଣିଗାହୀ', class: 5},
  {roll: 14, studentName: 'ସବିତା ବେଶ୍ରା', class: 5},
  {roll: 15, studentName: 'ଦୀପ୍ତିରାଣୀ ସାହୁ', class: 5},
  {roll: 16, studentName: 'ସୁଶାନ୍ତ ପଟ୍ଟନାୟକ', class: 5},
  {roll: 17, studentName: 'ସୁଜାତା ମିଶ୍ର', class: 5},
  {roll: 18, studentName: 'ମହେଶ ମୁଣ୍ଡା', class: 5},
  {roll: 19, studentName: 'ପ୍ରଶାନ୍ତ ପଣ୍ଡା', class: 5},
  {roll: 20, studentName: 'ଶିବାନୀ ମୁର୍ମୁ', class: 5},
  {roll: 21, studentName: 'ତ୍ରିପ୍ତିରେଖା ବେହେରା', class: 5},
  {roll: 22, studentName: 'ବିକ୍ରମାଦିତ୍ୟ ସାହୁ', class: 5},
  {roll: 23, studentName: 'ସୁଧାମୟୀ ପାଣିଗାହୀ', class: 5},
  {roll: 24, studentName: 'ଦେବାନନ୍ଦ ବାସ୍କେ', class: 5},
  {roll: 25, studentName: 'ଜଗନ୍ନାଥ ଦାସ', class: 5},
  {roll: 26, studentName: 'ପୂର୍ଣ୍ଣିମା ବେଶ୍ରା', class: 5},
  {roll: 27, studentName: 'ରାଜାଶ୍ରୀ ମହାନ୍ତି', class: 5},
  {roll: 28, studentName: 'ପ୍ରଶାନ୍ତି ସାହୁ', class: 5},
  {roll: 29, studentName: 'ଅର୍ଜୁନ ବେହେରା', class: 5},
  {roll: 30, studentName: 'ସୌମ୍ୟାଶ୍ରୀ ମିଶ୍ର', class: 5},
];

export const class6Students = [
  {roll: 1, studentName: 'ଅଭିନାଶ ମହାନ୍ତି', class: 6},
  {roll: 2, studentName: 'ରିମ୍ଜିମ ସୋରେନ', class: 6},
  {roll: 3, studentName: 'ସନ୍ଦିପ୍ତା ସାହୁ', class: 6},
  {roll: 4, studentName: 'ଆମିନା ବେଗମ', class: 6},
  {roll: 5, studentName: 'ପ୍ରକାଶ ପାଣିଗାହୀ', class: 6},
  {roll: 6, studentName: 'ଦୀପାଳି ବେଶ୍ରା', class: 6},
  {roll: 7, studentName: 'ଅଭିଷେକ ପଟ୍ଟନାୟକ', class: 6},
  {roll: 8, studentName: 'ମହମ୍ମଦ ଇମ୍ରାନ', class: 6},
  {roll: 9, studentName: 'ସ୍ମିତା ରାଉତ', class: 6},
  {roll: 10, studentName: 'ଅନୁରାଗ ଦାସ', class: 6},
  {roll: 11, studentName: 'ପୁର୍ଣ୍ଣିମା ସାହୁ', class: 6},
  {roll: 12, studentName: 'ବସନ୍ତ ହେମ୍ବ୍ରମ', class: 6},
  {roll: 13, studentName: 'ସଞ୍ଜୁକ୍ତା ପଣ୍ଡା', class: 6},
  {roll: 14, studentName: 'ଗୋପୀନାଥ ମୁର୍ମୁ', class: 6},
  {roll: 15, studentName: 'ଜୟନ୍ତୀ ବେହେରା', class: 6},
  {roll: 16, studentName: 'ସୁବ୍ରତ କୁମାର ସାହୁ', class: 6},
  {roll: 17, studentName: 'ଲିପିକା ପାଟ୍ଟନାୟକ', class: 6},
  {roll: 18, studentName: 'ପ୍ରଭାତୀ ମୁଣ୍ଡା', class: 6},
  {roll: 19, studentName: 'ଦେବାଶିଷ ମିଶ୍ର', class: 6},
  {roll: 20, studentName: 'ରାଜଶ୍ରୀ ପଟ୍ଟନାୟକ', class: 6},
  {roll: 21, studentName: 'ସୁଧୀର କୁମାର ଦାସ', class: 6},
  {roll: 22, studentName: 'ଚନ୍ଦ୍ରକାନ୍ତୀ ବେହେରା', class: 6},
  {roll: 23, studentName: 'ମନୋରମା ପଟ୍ଟନାୟକ', class: 6},
  {roll: 24, studentName: 'ଲକ୍ଷ୍ମୀକାନ୍ତ ମୁର୍ମୁ', class: 6},
  {roll: 25, studentName: 'ତୁଷାରିଣୀ ସାହୁ', class: 6},
  {roll: 26, studentName: 'ମଧୁସୂଦନ ପାଣିଗାହୀ', class: 6},
  {roll: 27, studentName: 'ସୁରଭି ପଣ୍ଡା', class: 6},
  {roll: 28, studentName: 'ପ୍ରିୟଦର୍ଶୀ ବେହେରା', class: 6},
  {roll: 29, studentName: 'ରଞ୍ଜନା ସୋରେନ', class: 6},
  {roll: 30, studentName: 'ବିଜୟ କୁମାର ସାହୁ', class: 6},
];
